### ISSUE TITLE
Expose `tribute-discord-service` for dev and prod

### ISSUE THREAD

**Issue by jtrein** [openlawteam/tribute-discord-service#45]
I'd like to be able for external services to access the HTTP API in:

- [x] `tribute-discord-prod-deployment`
- [x] `tribute-discord-dev-deployment`

@fforbeck, could you show me how to (sync or async) expose the `tribute-discord-service` for dev and prod? I only see the dev service under `Kubernetes Engine > Services & Ingress`.

@jdville03, if possible, I would like the subdomains:
- [x] ~`discord.tributelabs.xyz`~ `discord.thelao.io` (prod) 
- [x] ~`discord.dev.tributelabs.xyz`~ `discord.dev.thelao.io` (dev)

**Comment by fforbeck** [comment]
@jtrein sure thing.
In order to expose these service we need to create the ssl certificates with the subdomains in the k8s cluster.
Right now that cluster supports the `thelao.io` subdomain, we need to configure that to support the `tributelabs.xyz`. After that we can create the certificates, and add the services to the ingress file - that will make the services available to the external world. One thing to keep in mind is that anyone will be able to call these services, so it is important to have some sort of authorization/authentication in place.

**Comment by jtrein** [comment]
> In order to expose these services we need to create the ssl certificates with the subdomains in the k8s cluster.

@fforbeck Is this something I can do, now?

**Comment by fforbeck** [comment]
I believe so @jtrein , if you look at the lao-backends repo folder: `k8s/infra/dev/` you will see a file called: `certificates.yml`. You just need to append your new certificate there, give it a name and set the desired subdomain - gcp will handle the creation of the certificate for you. 

Then in the `k8s/infra/dev/ingress.yml` you need to add a new entry that will bind the public hostname to the service name and port. If you open a PR we can double check the configs, and test in dev first.

**Comment by jdville03** [comment]
Sounds good @jtrein. In addition to what @fforbeck detailed above we would just need to add the new A records in Cloudflare.

**Comment by jtrein** [comment]
@fforbeck OK, dev PR is up for your review whenever you are free :-) https://github.com/openlawteam/lao-backends/pull/589

**Comment by jtrein** [comment]
@jdville03 would you mind adding those A Records, or showing me where/how to do it? I don't have access, fyi.

**Comment by jdville03** [comment]
`A` record has been added in Cloudflare for the dev service.

![Screen Shot 2021-11-18 at 1 21 23 PM](https://user-images.githubusercontent.com/22142472/142498926-b21cad05-46cb-499c-a0ef-6b375aebd1e2.png)

**Comment by jtrein** [comment]
@jdville03 Think you could hook me up with an A Record now for production? :-) `discord.thelao.io`

**Comment by jtrein** [comment]
Actually, @fforbeck took care of this!

**Comment by fforbeck** [comment]
@jtrein, I just created the missing configs: https://github.com/openlawteam/lao-backends/pull/593
and manually deployed to prod from my env. We just need to merge that PR.
